### ISSUE TITLE
Environment install lacks dependencies

### ISSUE THREAD

**Issue by cversteeg** [NeuralAnalysis/PyalData#87]
Import statements used in the demo are not in the general environment installation. (xarray, at least).
I might also suggest that a docker container be made, if it's not a huge hassle.

**Comment by cversteeg** [comment]
mat73 also on the list.

**Comment by raeedcho** [comment]
Oh also, I highly recommend using [pipenv](https://pipenv.pypa.io/en/latest/) instead of Docker for managing simple python environments (though I suppose conda works too, if you're using Anaconda).

**Comment by bagibence** [comment]
Thanks for raising this! Yes, we'll definitely need to document the dependencies.
I didn't include xarray because it's only used in the demo, the internals of pyaldata don't rely on it, and -- even though it's one of my favorite packages -- I didn't want to force it on the user.

I agree with @raeedcho in that I don't see why Docker would be needed.

I'm not sure about the Python version. My guess now would be anything >=3.6 because we use f-strings quite a lot. I'm on 3.8 and it works fine, so we'll just have to test 3.6 and 3.9.

That said, @catiafortunato discovered that the `trial_average` function doesn't work with the newest version of pandas, so that will have to be fixed and indicated somewhere.

**Comment by bagibence** [comment]
Fixed by #141 and #143

- #141 updates `trial_average` to work with pandas v2
- #143 specifies some dependencies that work
